### ISSUE TITLE
~/.hammerspoon/hs/spaces.lua:99: attempt to index a nil value (local 'contents')

### ISSUE THREAD

**Issue by KysonGeek** [asmagill/hs._asm.spaces#1]
2022-04-06 17:37:06: *** ERROR: /Users/\~/.hammerspoon/hs/spaces.lua:99: attempt to index a nil value (local 'contents')
stack traceback:
	/Users/\~/.hammerspoon/hs/spaces.lua:99: in local 'getDockExitTemplates'
	/Users/\~/.hammerspoon/hs/spaces.lua:104: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/\~/.hammerspoon/init.lua:2: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by KysonGeek** [comment]
spaces.lua 99
The locale expects to be /System/Library/CoreServices/Dock.app/Contents/Resources/
The truth is /System/Library/CoreServices/Dock.app/Contents/XPCServices/DockHelper.xpc/Contents/Resources

**Comment by asmagill** [comment]
What macOS version are you running? From the Hammerspoon console, you can type `hs.host.operatingSystemVersionString()` to get the formal version number.

Are you running the latest release version of Hammerspoon? If so, then spaces is now part of the core application and you can remove this external module from your system:

  * If you built it yourself, then type `make uninstall` while in the source directory (preceded by `PREFIX=...` if you used that when installing).

  * If you installed one of the pre-compiled zip files, then go into your hammerspoon config directory (usually `~/.hammerspoon`) and type the following:
~~~lua
% cd hs
% rm -fr spaces.* libspaces.*
~~~

Now fully quit and restart Hammerspoon and see if the problem persists.

If the problem persists, in addition to the operating system version, please provide the output from each of the following from the Hammerspoon console as well:
* `hs.host.locale.preferredLanguages()`
* `hs.host.locale.current()`
* `hs.application.applicationsForBundleID("com.apple.dock")[1]:path()`

**Comment by asmagill** [comment]
I'm going to close this, since it's been over two weeks, but reopen or submit a new issue if you're still having problems. You may also want to check out the latest version here or in the Hammerspoon pull requests as well to see if the recent fixes take care of your problem.
