### ISSUE TITLE
"moveWindowToSpace" function is not working properly. 

### ISSUE THREAD

**Issue by CassandraCat** [asmagill/hs._asm.spaces#6]
e.g., assume my current space ID is 3, I use moveWindowToSpace to move a window to space 3 but it doesn't take effect.

**Comment by asmagill** [comment]
This is addressed in https://github.com/Hammerspoon/hammerspoon/pull/3638 for the Hammerspoon application, and I have fixed it for this module as well; however, I don't know how much longer this will remain as a separate repository, as it has been formally adopted by Hammerspoon and doesn't provide any more functionality than the version there.
